complete -c exa -l help -s '?' -d "show list of command-line options"
complete -c exa -l version -s v -d "show version of exa"
complete -c exa -l oneline -s 1 -d "display one entry per line"
complete -c exa -l long -s l -d "display extended file metadata as a table"
complete -c exa -l grid -s G -d "display entries as a grid (default)"
complete -c exa -l across -s x -d "sort the grid across, rather than downwards"
complete -c exa -l recurse -s R -d "recurse into subdirectories"
complete -c exa -l tree -s T -d "recurse into subdirectories as a tree"
complete -c exa -l classify -s F -d "display type indicator by file names"
complete -c exa -l color -a "auto never always" -f -d "when to use terminal colors" -r
complete -c exa -l color-scale -d "highlight levels of file sizes distinctly"
complete -c exa -l all -s a -d "show hidden and 'dot' files"
complete -c exa -l list-dirs -s d -d "list directories like regular files"
complete -c exa -l reverse -s r -d "reverse the sort order"
complete -c exa -l sort -s s -a "name Name extension Extension size type modified accessed created inode none" -f -r -d "which field to sort by"
complete -c exa -l group-directories-first -d "list directories before other files"
complete -c exa -l ignore-globs -s I -a "" -r -d "glob patterns (pipe-separated) of files to ignore"
